#!/bin/sh

### BEGIN INIT INFO
# Provides:          blackfly
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Script for controlling blackfly daemon
# Description:       The script support start and stop operations
### END INIT INFO

# Change the next 3 lines to suit where you install your script and what you want to call it
NAME=BlackflyTestSuite
DIR=/opt/BlackflyTestSuite
DAEMON=$DIR/BlackflyTestSuite.py
DAEMON_NAME=blackfly
PYTHON_BIN=/usr/bin/python

# This next line determines what user the script runs as.
# Root generally not recommended but necessary if you are using the Raspberry Pi GPIO from Python.
DAEMON_USER=blackfly

# The process ID of the script when it runs is stored here:
PIDFILE=/var/run/$DAEMON_NAME.pid

. /etc/rc.d/init.d/functions

do_start () {
    log_daemon_msg "Starting system $DAEMON_NAME daemon"
    cd $DIR
    daemon --pidfile $PIDFILE --user $DAEMON_USER "$PYTHON_BIN $DAEMON &"
    RETVAL=$?
    pid=`ps -ef | grep $NAME | awk 'NR==1{print $2}'`
    if [ -n "$pid" ]; then
                echo $pid > "$PIDFILE"
    fi
    echo
    return $RETVAL

}
do_stop () {
    echo -n $"Stopping $NAME: "
    killproc -p "$PIDFILE" -d 10 "$DAEMON"
    RETVAL="$?"
    echo
    [ $RETVAL = 0 ] && rm -f "$PIDFILE"
    return "$RETVAL"
}

case "$1" in

    start|stop)
        do_${1}
        ;;

    restart|reload|force-reload)
        do_stop
        do_start
        ;;

    status)
	status_of_proc "$DAEMON_NAME" "$DAEMON" && exit 0 || exit $?
        ;;
    *)
        echo "Usage: /etc/init.d/$DAEMON_NAME {start|stop|restart|status}"
        exit 1
	;;

esac
exit $RETVAL
